### PR TITLE
Added support for widgets, custom stylesheet

### PR DESCRIPTION
**Pull request by pnoeric**
Hi Lukas-- I added just a bit of code to support widgets above or below the content, and a custom style sheet. (We use your plugin while a site is "Coming Soon," and often want to include a little newsletter signup widget. I could also see someone potentially wanting to add a video to their page.)

I also added the ability to inject a little code snippet on the page-- for example, Google Analytics tracking code.

In the spirit of keeping the code very simple and light, I tried to make the footprint of my changes as minimal as possible.

I also took the liberty of updating the README, changelog, etc with some new info in the FAQ section, info about the new filter, and a new version number (just trying to make it easier for you!). Of course feel free to ignore, rewrite or whatever.

Would love to hear your thoughts and hope you like my improvements.

best
Eric Mueller - switchplus.ch

### CODE REVIEW

**Comment by lukasjuhas** [comment]
Hi Eric,

Thanks for your input! If you don't mind I will review later this month as I'll be away from tomorrow. 

I had a brief look though, nice work.

I'll get back to you when I'm back. Thanks!

Lukas

**Comment by pnoeric** [comment]
Thanks Lukas, sounds good. 👍🏻

**Comment by pnoeric** [comment]
I've also just added support for the [Analytify plugin](https://wordpress.org/plugins/wp-analytify/), to automatically add the Google Analytics tracking code.

**Comment by lukasjuhas** [comment]
Hey @pnoeric, great work, thanks, I will go through the code and tidy up some of the bits if you don't mind, If I'll have any questions or suggestions, I'll let you know! 

Sorry, it took me longer to get to this but I'm hoping to push 2.4 shortly.

**Pull request merged**
